// <auto-generated />
namespace Mar9_一對多.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatesalt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatesalt));
        
        string IMigrationMetadata.Id
        {
            get { return "202103260705436_update salt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
